# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            parse | a blog by aadith v menon
tagline:          'a blog of a coder'
description:      'parse | a blog by aadith v menon'
url:              http://parse.cf
baseurl:          '/'
paginate:         5

author:
  name:           'Aadith V Menon'
  url:            https://twitter.com/aadithvmenon

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/cysys/cysys.github.io
